name: trading_bot_watcher_73
language: python
runtimeConfig:
  start:
    - "python main.py"
database:
  migrate:
    - echo 'No migrations specified'
telemetry:
  logs:
    logLevel: INFO
